Mcho/dev
PrestaShop/ps_banner pull request #30
Opened 2021-03-19 09:48 UTC by Mch0

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | on reset or uninstall then install, modules are hooked in the wrong place
| Type?         | bug fix
| BC breaks?    | yes
| Deprecations? | yes
| Fixed ticket? | Fixes PrestaShop/Prestashop#20748
| How to test?  | Steps to reproduce the behavior:

Go to BO > Module Manager page > Search for the slider module
Click on reset
Go to FO > Home page
See error => the banner is at the last position on the home page

2021-03-19 09:48 UTC, Mch0 commented
mistake not branch master but dev branch for PR sorry

2021-03-19 09:57 UTC, PierreRambaud requested changes
I'm not sure it's a bug :thinking: You reset or reinstall a module, the position is automatically set at the end, nothing mean when you install/reset these modules your theme want to be set at position X.

You've access to the Module Positions page to change the value.

2021-03-20 08:55 UTC, Mch0 commented
im so sad, could you close issue in this case ?

2021-05-16 19:36 UTC, matks requested changes
@Mch0 The exploration of the issue https://github.com/PrestaShop/PrestaShop/issues/20748 continue, you can contribute to the discussion 😉 if you want to.

However I agree with @PierreRambaud that this Pull Request is likely not the good way to fix the issue.

2021-05-17 08:18 UTC, closed without merging