Add badges in README and update links
PrestaShop/ps_banner pull request #54
Opened 2023-06-01 07:18 UTC by justeen35

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Add badges in README and update links
| Type?         | improvement
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | 
| How to test?  | Look at the README :)

2023-06-01 07:45 UTC, mflasquin requested changes, later dismissed

2023-06-01 07:45 UTC, mflasquin commented on Readme.md
> +[contribution-guidelines]: https://devdocs.prestashop.com/8/contribute/contribution-guidelines/project-modules/
```suggestion
[contribution-guidelines]: https://devdocs.prestashop-project.org/8/contribute/contribution-guidelines/project-modules/
```

2023-06-01 07:51 UTC, justeen35 commented on Readme.md
> +[contribution-guidelines]: https://devdocs.prestashop.com/8/contribute/contribution-guidelines/project-modules/
Fixed, thank you

2023-06-01 07:51 UTC, justeen35 commented
@mflasquin All good

2023-06-01 08:55 UTC, matks approved these changes

2023-06-01 09:30 UTC, matks commented
Looks like PHPStan is finding a problem however unrelated to this PR 🤔

2023-06-01 13:37 UTC, M0rgan01 commented
@matks Since the switch to Prestashop v8, the method that phpstan provides no longer exists.

https://github.com/PrestaShop/PrestaShop/blob/e57ae6124e0ad897ff74078b74d7a72bbf835b54/classes/Configuration.php#L257-L263 in 1.7.8.x branch

Need another PR to fix the problem.

2023-06-08 07:06 UTC, kpodemski approved these changes

2023-06-08 07:07 UTC, merged

2023-06-08 07:08 UTC, kpodemski commented
thanks @justeen35 :)